fix(dns): add a lower-bound negative TTL (#4449)
see linkerd/linkerd2#14954.

some user reports describe situations in which, when the linkerd control
plane's destination controller is OOM-killed, DNS resolution can
momentarily cause the proxy to compute a negative-TTL duration of zero.

this causes a panic in production environments, because
`tokio::time::interval` asserts that it has not been provided a duration
of zero. this manifests in errors that look like this:

```
thread 'main' panicked at linkerd/app/core/src/control.rs:118:49: period must be non-zero.
```

this commit introduces a minimum negative TTL that will be used when
backing off from resolution errors.

this commit moves the logic responsible for enforcing a minimum TTL
(added linkerd/linkerd2-proxy#3807) from the outer layer in
`linkerd-dns-resolve` and into the `linkerd-dns` library.

this helps us reuse/consolidate the same logic for negative TTL's when
recovering from resolution errors, and will facilitate making this
configurable in the future, should we so desire.

X-Ref: linkerd/linkerd2-proxy#3807
Signed-off-by: katelyn martin <kate@buoyant.io>