fix(dns): check for negative_ttl of zero
see linkerd/linkerd2#14954.

some user reports describe situations in which, when the linkerd control
plane's destination controller is OOM-killed, DNS resolution can
momentarily cause the proxy to compute a negative-TTL duration of zero.

this causes a panic in production environments, because
`tokio::time::interval` asserts that it has not been provided a duration
of zero.

this manifests in errors that look like this:

```
thread 'main' panicked at linkerd/app/core/src/control.rs:118:49: period must be non-zero.
```

this commit patches `linkerd-dns::ResolveError::negative_ttl()` so that
it will now log a warning and instead return `None` when a negative TTL
of zero is encountered. a shared `duration_from_error()` helper
(bikeshedding welcome) helps do this for both A/AAAA and SRV records.

X-Ref: linkerd/linkerd2-proxy#3807
Signed-off-by: katelyn martin <kate@buoyant.io>