error: Make backoff streams infallible
`error::Recover's1 Backoff stream type is fallible, but only because
this was required by the old API.

This change makes the backoff stream infallible.