meshtls: replace build script with `compile_error!` macro
Currently, the `linkerd-meshtls` crate uses a build script to ensure
that at least one TLS implementation feature flag is enabled when
compiling the crate. This can be done much more simply using the
`compile_error!` macro.

Removing the build script may make compilation (very slightly) faster,
because the build script no longer needs to be compiled. Also, the error
message is a bit nicer, since it just prints the error, rather than
"failed to run custom build command".

Here's the compiler output before this change:

```
:; cargo build -p linkerd-meshtls --no-default-features
   Compiling linkerd-meshtls v0.1.0 (/home/eliza/Code/linkerd2-proxy/linkerd/meshtls)
   Compiling linkerd-tls v0.1.0 (/home/eliza/Code/linkerd2-proxy/linkerd/tls)
error: failed to run custom build command for `linkerd-meshtls v0.1.0 (/home/eliza/Code/linkerd2-proxy/linkerd/meshtls)`

Caused by:
  process didn't exit successfully: `/home/eliza/Code/linkerd2-proxy/target/debug/build/linkerd-meshtls-d2a634fb5bc47eea/build-script-build` (exit status: 1)
  --- stderr
  Error: "at least one of the following TLS implementations must be enabled: 'rustls'"
```

...and after:

```
:; cargo build -p linkerd-meshtls --no-default-features
   Compiling linkerd-meshtls v0.1.0 (/home/eliza/Code/linkerd2-proxy/linkerd/meshtls)
error: at least one of the following TLS implementations must be enabled: 'rustls'
 --> linkerd/meshtls/src/lib.rs:6:1
  |
6 | compile_error!("at least one of the following TLS implementations must be enabled: 'rustls'");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```